services:
  app:
    build:
      context: ./  # プロジェクトルートをコンテキストに設定
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html  # ホストのプロジェクトをコンテナにマウント
    expose:
      - "9000"
    user: "sail"
    networks:
      - internal

  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - internal

  db:
    image: mysql:8.0
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
      MYSQL_USER: '${DB_USERNAME:-laravel}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
    networks:
      - internal

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"  # Webインターフェース
      - "1025:1025"  # SMTP サーバー
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  db_data:
