services:
  app:
    build:
      context: ./  # プロジェクトルートをコンテキストに設定
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html  # ホストのプロジェクトをコンテナにマウント
    expose:
      - "9000"
    user: "sail"
    
    networks:
      - internal

  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      # 必要な設定ファイルを正しい場所にマウント
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    ports:
      - "8000:80" # ローカルポート8000でNginxにアクセス
    depends_on:
      - app # appコンテナの起動を待つ
    networks:
      - internal

networks:
  internal:
    driver: bridge